spring:
  profiles:
    active: dev #\u9ED8\u8BA4\u4E3A\u5F00\u53D1\u73AF\u5883
  aop:
    auto: true
  application:
    name: openpsd

jwt:
  tokenHeader: Authorization #JWT\u5B58\u50A8\u7684\u8BF7\u6C42\u5934
  secret: mall-admin-secret #JWT\u52A0\u89E3\u5BC6\u4F7F\u7528\u7684\u5BC6\u94A5
  expiration: 604800 #JWT\u7684\u8D85\u671F\u9650\u65F6\u95F4(60*60*24*7)
  tokenHead: Bearer  #JWT\u8D1F\u8F7D\u4E2D\u62FF\u5230\u5F00\u5934
logging:
  level:
    root: info #\u65E5\u5FD7\u914D\u7F6EDEBUG,INFO,WARN,ERROR
    com.caler.zkl.openpsd.mapper: debug
    com.caler.zkl.openpsd.controller: debug
#  file: demo_log.log #\u914D\u7F6E\u65E5\u5FD7\u751F\u6210\u8DEF\u5F84
#  path: /var/logs #\u914D\u7F6E\u65E5\u5FD7\u6587\u4EF6\u540D\u79F0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: true
secure:
  ignored:
    urls: #\u5B89\u5168\u8DEF\u5F84\u767D\u540D\u5355
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /druid/**
      - /info/*
      - /doc.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /user/login
      - /user/register
      - /user/info
      - /user/logout
      - /minio/upload
debug: true

system:
  ctrl:
    urls:
      - /doc.html
      - /druid/sql.html
swagger:
  production: false
  basic:
    enable: true
    username: admin
    password: 123

# 在默认情况下大多数Actuator的端点并没有完全公开，这里我将所有端点都进行公开进行管理
management:
  endpoints:
    web:
      exposure:
        include: "*"
