package com.caler.zkl.openpsd.mapper;

import com.caler.zkl.openpsd.bean.ErrorMsg;
import com.caler.zkl.openpsd.bean.ErrorMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErrorMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    long countByExample(ErrorMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int deleteByExample(ErrorMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int insert(ErrorMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int insertSelective(ErrorMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    List<ErrorMsg> selectByExampleWithBLOBs(ErrorMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    List<ErrorMsg> selectByExample(ErrorMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    ErrorMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") ErrorMsg record, @Param("example") ErrorMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ErrorMsg record, @Param("example") ErrorMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByExample(@Param("record") ErrorMsg record, @Param("example") ErrorMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByPrimaryKeySelective(ErrorMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ErrorMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByPrimaryKey(ErrorMsg record);
}