package com.caler.zkl.openpsd.mapper;

import com.caler.zkl.openpsd.bean.MemberLoginLog;
import com.caler.zkl.openpsd.bean.MemberLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    long countByExample(MemberLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int deleteByExample(MemberLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int insert(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int insertSelective(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    List<MemberLoginLog> selectByExample(MemberLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    MemberLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") MemberLoginLog record, @Param("example") MemberLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByExample(@Param("record") MemberLoginLog record, @Param("example") MemberLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByPrimaryKeySelective(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByPrimaryKey(MemberLoginLog record);
}