package com.caler.zkl.openpsd.mapper;

import com.caler.zkl.openpsd.bean.ProductUtil;
import com.caler.zkl.openpsd.bean.ProductUtilExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductUtilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    long countByExample(ProductUtilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int deleteByExample(ProductUtilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int insert(ProductUtil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int insertSelective(ProductUtil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    List<ProductUtil> selectByExample(ProductUtilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    ProductUtil selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProductUtil record, @Param("example") ProductUtilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByExample(@Param("record") ProductUtil record, @Param("example") ProductUtilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByPrimaryKeySelective(ProductUtil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    int updateByPrimaryKey(ProductUtil record);
}