package com.caler.zkl.openpsd.mapper;

import com.caler.zkl.openpsd.bean.ResourceCategory;
import com.caler.zkl.openpsd.bean.ResourceCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    long countByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    int deleteByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    int insert(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    int insertSelective(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    List<ResourceCategory> selectByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    ResourceCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") ResourceCategory record, @Param("example") ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    int updateByExample(@Param("record") ResourceCategory record, @Param("example") ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    int updateByPrimaryKeySelective(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Fri May 01 17:43:56 CST 2020
     */
    int updateByPrimaryKey(ResourceCategory record);
}