package com.caler.zkl.openpsd.mapper;

import com.caler.zkl.openpsd.bean.RoleResourceRelation;
import com.caler.zkl.openpsd.bean.RoleResourceRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleResourceRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    long countByExample(RoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int deleteByExample(RoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int insert(RoleResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int insertSelective(RoleResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    List<RoleResourceRelation> selectByExample(RoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    RoleResourceRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoleResourceRelation record, @Param("example") RoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int updateByExample(@Param("record") RoleResourceRelation record, @Param("example") RoleResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int updateByPrimaryKeySelective(RoleResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int updateByPrimaryKey(RoleResourceRelation record);
}