package com.caler.zkl.openpsd.mapper;

import com.caler.zkl.openpsd.bean.RoleMenuRelation;
import com.caler.zkl.openpsd.bean.RoleMenuRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMenuRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    long countByExample(RoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int deleteByExample(RoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int insert(RoleMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int insertSelective(RoleMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    List<RoleMenuRelation> selectByExample(RoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    RoleMenuRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoleMenuRelation record, @Param("example") RoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int updateByExample(@Param("record") RoleMenuRelation record, @Param("example") RoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int updateByPrimaryKeySelective(RoleMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_relation
     *
     * @mbg.generated Fri May 01 13:15:31 CST 2020
     */
    int updateByPrimaryKey(RoleMenuRelation record);
}