package com.caler.zkl.openpsd.bean;

import java.io.Serializable;

public class ErrorMsg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_msg.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_msg.code
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_msg.time
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_msg.ip
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_msg.userid
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_msg.text
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_msg.position
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_msg.id
     *
     * @return the value of error_msg.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_msg.id
     *
     * @param id the value for error_msg.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_msg.code
     *
     * @return the value of error_msg.code
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_msg.code
     *
     * @param code the value for error_msg.code
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_msg.time
     *
     * @return the value of error_msg.time
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_msg.time
     *
     * @param time the value for error_msg.time
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_msg.ip
     *
     * @return the value of error_msg.ip
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_msg.ip
     *
     * @param ip the value for error_msg.ip
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_msg.userid
     *
     * @return the value of error_msg.userid
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_msg.userid
     *
     * @param userid the value for error_msg.userid
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_msg.text
     *
     * @return the value of error_msg.text
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_msg.text
     *
     * @param text the value for error_msg.text
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_msg.position
     *
     * @return the value of error_msg.position
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_msg.position
     *
     * @param position the value for error_msg.position
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_msg
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", time=").append(time);
        sb.append(", ip=").append(ip);
        sb.append(", userid=").append(userid);
        sb.append(", text=").append(text);
        sb.append(", position=").append(position);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}