package com.caler.zkl.openpsd.bean;

import java.io.Serializable;

public class MemberLevel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_level.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_level.name
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_level.default_status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Integer defaultStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_level.note
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_level
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_level.id
     *
     * @return the value of member_level.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_level.id
     *
     * @param id the value for member_level.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_level.name
     *
     * @return the value of member_level.name
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_level.name
     *
     * @param name the value for member_level.name
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_level.default_status
     *
     * @return the value of member_level.default_status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Integer getDefaultStatus() {
        return defaultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_level.default_status
     *
     * @param defaultStatus the value for member_level.default_status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setDefaultStatus(Integer defaultStatus) {
        this.defaultStatus = defaultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_level.note
     *
     * @return the value of member_level.note
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_level.note
     *
     * @param note the value for member_level.note
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_level
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", defaultStatus=").append(defaultStatus);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}