package com.caler.zkl.openpsd.bean;

import java.io.Serializable;

public class Message implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_on
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String sendOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_on
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private byte[] createOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_on
     *
     * @return the value of message.send_on
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getSendOn() {
        return sendOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_on
     *
     * @param sendOn the value for message.send_on
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setSendOn(String sendOn) {
        this.sendOn = sendOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message
     *
     * @return the value of message.message
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message
     *
     * @param message the value for message.message
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_on
     *
     * @return the value of message.create_on
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public byte[] getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_on
     *
     * @param createOn the value for message.create_on
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setCreateOn(byte[] createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", sendOn=").append(sendOn);
        sb.append(", status=").append(status);
        sb.append(", message=").append(message);
        sb.append(", createOn=").append(createOn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}