package com.caler.zkl.openpsd.bean;

import java.io.Serializable;

public class ProductUtil implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_util.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_util.util_name
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private String utilName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_util.status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_util.sort
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_util.id
     *
     * @return the value of product_util.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_util.id
     *
     * @param id the value for product_util.id
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_util.util_name
     *
     * @return the value of product_util.util_name
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public String getUtilName() {
        return utilName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_util.util_name
     *
     * @param utilName the value for product_util.util_name
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setUtilName(String utilName) {
        this.utilName = utilName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_util.status
     *
     * @return the value of product_util.status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_util.status
     *
     * @param status the value for product_util.status
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_util.sort
     *
     * @return the value of product_util.sort
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_util.sort
     *
     * @param sort the value for product_util.sort
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_util
     *
     * @mbg.generated Sun Apr 26 11:05:26 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", utilName=").append(utilName);
        sb.append(", status=").append(status);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}